name: 'esrgan'

model:
  _target_: tamrfsits.components.datewise.DateWiseSITSModule
  model:
    _target_ : tamrfsits.core.esrgan.ESRGANGenerator
    nb_bands: ${datamodule.nb_hr_channels}
    upsampling_factor: 1.
    out_nb_bands: ${training_module.nb_latent_features}
    latent_size: 64
    num_basic_blocks: 1
    growth_channels: 32
    residual_scaling: 0.2
