name: 'carn'

model:
  _target_: tamrfsits.components.datewise.DateWiseSITSModule
  model:
    _target_ : tamrfsits.core.carn.CARN
    config:
      _target_: tamrfsits.core.carn.CARNConfig
      nb_bands: ${datamodule.nb_lr_channels}
      out_nb_bands: ${training_module.nb_latent_features}
      upsampling_factor: ${datamodule.hr_lr_resolution_ratio}
      nb_features_per_factor: 32
      groups: 4
      shared_weights: true
      nb_cascading_blocks: 3
      nb_eres_blocks_per_cascading_block: 3
      kernel_size: 3
      leaky_relu_slope: 0.2
